version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3200:3306"
  backend:
    build: ./backend
    depends_on:
      - db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/fytics/backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: backend.dev_settings
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/fytics/frontend
      - node-modules:/fytics/frontend/node_modules
volumes:
 node-modules: